In [1]:
import numpy as np

In [3]:
def dotproduct(u,v):
    assert u.shape[0]==v.shape[0]
    n=u.shape[0]
    result=0
    for i in range(n):
        result=result+u[i]*v[i]
    return result

In [17]:
v=np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0],
])

In [11]:
u=np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1],
    ])

In [14]:
def matrix_vector(u,v):
    assert u.shape[1]==v.shape[0]
    k=u.shape[0]
    result=np.zeros(k)
    for i in range(k):
        result[i]=u
    return result

In [27]:
def matrix_matrix(u,v):
    assert u.shape[1]==v.shape[0]
    k=u.shape[0]
    result=np.zeros((u.shape[0],v.shape[1]))
    for i in range(k):
        ui=u[:,i]
        result[:,i]=matrix_vector(u,v[:,i])
    return result

In [28]:
matrix_matrix(u,v)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [29]:
u.dot(v)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [31]:
I=np.eye(4)

In [33]:
u.dot(I)

array([[2., 4., 5., 6.],
       [1., 2., 1., 2.],
       [3., 1., 2., 1.]])

In [35]:
sq=v[[0,1,2]]

In [37]:
vs=np.linalg.inv(sq)

In [38]:
vs.dot(sq)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])