In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/python/3.14.2/lib/python3.14/site-packages/numpy/__init__.py'>

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [9]:
a=np.array([1,2,3,4,6,7])

In [11]:
print(a[2])

3


In [12]:
a[1]=10

In [13]:
a

array([ 1, 10,  3,  4,  6,  7])

In [16]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [20]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
n=np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5]
])

In [25]:
print(n[0,1])

2


In [27]:
n[1]=[1,1,1]

In [28]:
n

array([[1, 2, 3],
       [1, 1, 1],
       [3, 4, 5]])

In [30]:
n[:,1]

array([2, 1, 4])

In [34]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [35]:
a=np.arange(5)

In [44]:
b=(10+(a*2))**2
a=a+b

In [45]:
a>=b

array([ True,  True,  True,  True,  True])

In [47]:
a[a<b]

array([], dtype=int64)

In [51]:
print(a.min())

100


In [52]:
print(a.sum())

1030


In [53]:
print(a.mean())

206.0
